apiVersion: v1
kind: Service
metadata:
  name: kibana-k8s
  namespace: elasticsearch
  labels:
    k8s-app: kibana-k8s
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "Kibana"
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: kibana-k8s
