kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
parameters:
    monitors: 10.32.3.61:6789,10.32.3.62:6789,10.32.3.63:6789   
    adminId: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: default 
    claimRoot: /pvc-volumes
